<a href="https://colab.research.google.com/github/ktgokr/machineLearning/blob/main/%EC%9C%A0%EB%B0%A9%EC%95%94%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from  sklearn.datasets import load_breast_cancer
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


In [ ]:
breast_cancer = load_breast_cancer()
print(breast_cancer)

In [3]:
#input numpy array를 설정
breast_cancer_data = breast_cancer.data
print(type(breast_cancer_data))
print(breast_cancer_data.shape)
print(breast_cancer_data)

<class 'numpy.ndarray'>
(569, 30)
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [4]:
#target numpy array를 설정
breast_cancer_label = breast_cancer.target
print(type(breast_cancer_label))
print(breast_cancer_label)
print(breast_cancer_label)


<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(breast_cancer_data, breast_cancer_label, test_size=0.2)
print('Training Data:', X_train.shape)
print('Training Label', Y_train.shape)
print('Test Data', X_test.shape)
print('Test Label', Y_test.shape)

Training Data: (455, 30)
Training Label (455,)
Test Data (114, 30)
Test Label (114,)


In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dt = DecisionTreeClassifier(max_depth=100, max_features=5)# max_depth, max_feature

dt.fit(X_train, Y_train)
y_pred = dt.predict(X_test)

print('예측 정확도: %.2f' %accuracy_score(Y_test, y_pred))

예측 정확도: 0.96


In [18]:
from sklearn.svm import SVC


svc = SVC(C= 2.0, kernel='linear') #svc = SVC(c: , kernel:, gamma)

svc.fit(X_train, Y_train)
y_pred = dt.predict(X_test)

print('예측 정확도: %.2f' %accuracy_score(Y_test, y_pred))

예측 정확도: 0.96


In [22]:
from sklearn.ensemble import RandomForestClassifier


rf = RandomForestClassifier(n_estimators =300) # n_estimators = , max_depth= , max_features =

rf.fit(X_train, Y_train)
y_pred = dt.predict(X_test)

print('예측 정확도: %.2f' %accuracy_score(Y_test, y_pred))

예측 정확도: 0.96
